FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /opt

# Install Java + basics
RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-17-jre-headless \
    unzip \
    ca-certificates \
    curl \
  && rm -rf /var/lib/apt/lists/*



COPY readyapi/tools/ReadyAPI-TestEngine.zip /opt/ReadyAPI-TestEngine.zip

# Unzip into /opt/readyapi
RUN mkdir -p /opt/readyapi && \
    unzip /opt/ReadyAPI-TestEngine.zip -d /opt/readyapi && \
    rm /opt/ReadyAPI-TestEngine.zip


WORKDIR /work
COPY KafkaAPITesting-readyapi-project.xml 

# Create artifacts folder for reports
RUN mkdir -p /work/artifacts

#   READYAPI_LICENSE_KEY=xxxxx


CMD ["/opt/readyapi/bin/testrunner.sh", "-h"]
